def fn_clean_up():
    print("invoked clean-up function")

import atexit
atexit.register(fn_clean_up)

print('''
Do sth here ...
Do sth here ...
Do sth here ...
Do sth here ...
Do sth here ...
Do sth here ...
Do sth here ...
''')
